package simu.model;


public enum TapahtumanTyyppi {
	CHECKIN_ENTER,
	CHECKIN_START,
	CHECKIN_END_SELF,
	CHECKIN_END_BAGGAGE,
	
	BAGGAGE_ENTER,
	BGGAGE_START,
	BAGGAGE_END,
	
	SECURITYCHECK_ENTER,
	SECURITYCHECK_START,
	SECURITYCHECK_END_SCHENGE,
	SECURITYCHECK_END_INTERNATIONAL,
	
	PASSPORTCONTROL_ENTER,
	PASSPORTCONTROL_START,
	PASSPORTCONTROL_END,
	
	TICKETINSPECTION_ENTER,
	TICKETINSPECTION_START, 
	TICKETINSPECTION_END,
	
	SCHENGE_PLANE_DEPARTING,
	INTERNATIONAL_PLANE_DEPARTING
}
