package simu.model;

// TODO:
// Tapahtumien tyypit määritellään simulointimallin vaatimusten perusteella
public enum TapahtumanTyyppi {
	CHECKIN_ENTER_SELF,
	CHECKIN_ENTER_LUGGAGE,
	CHECKIN_START_SELF,
	CHECKIN_START_LUGGAGE,
	CHECKIN_END_SELF,
	CHECKIN_END_LUGGAGE,
	
	LUGGAGE_ENTER,
	LUGGAGE_START,
	LUGGAGE_END,
	
	SECURITYCHECK_ENTER,
	SECURITYCHECK_START,
	SECURITYCHECK_END_SCHENGE,
	SECURITYCHECK_END_INTERNATIONAL,
	
	PASSPORTCONTROL_ENTER,
	PASSPORTCONTROL_START,
	PASSPORTCONTROL_END,
	
	TICKETINSPECTION_ENTER,
	TICKETINSPECTION_START,
	TICKETINSPECTION_END,
}
